
services:
  postgres:
    image: postgres:16-alpine
    container_name: pikzee-postgres
    environment:
      POSTGRES_USER: nikhilenigma
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pikzee_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pikzee-network

  nginx:
    image: nginx:stable-alpine
    container_name: pikzee-nginx
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pikzee-network


volumes:
  pgdata:

networks:
  pikzee-network:
    driver: bridge
